### ISSUE TITLE
API for unit tests

### ISSUE THREAD

**Issue by mrjackdavis** [saasquatch/bunshi#10]
Hey!

(Firstly, this library is bloody amazing. IMO it should be first class for jotai.)

I have complicated molecules that I'd like to unit test. I'd appreciate some simple react-less API for doing so.

I need the equivalent of `useMolecule` to get the output of a molecule for a given scope. I noticed `createStore` used in [store.test.ts](https://github.com/saasquatch/jotai-molecules/blob/main/src/store.test.ts). Perhaps exposing that would work? 

Would you be open to a PR?

**Comment by loganvolkers** [comment]
Hey @mrjackdavis thanks for the positive feedback and thanks for the question. Sorry for the long wait. Looks like others have requested something similar in #20.

We'll be exposing the store api (called the injector API) in the next version to be released soon.
