### ISSUE TITLE
withScope types are hard to use

### ISSUE THREAD

**Issue by mrjackdavis** [saasquatch/bunshi#11]
Consider the following scenario

```
type SomeType = {};
const myScope = createScope<SomeType | undefined>(undefined);

// ...
const myScopeThing:SomeType = {};
const myThing = useMolecule(someMolecule,{
  withScope:[myScope,myScopeThing]
})
```

`withScope:[myScope,myScopeThing]` throws an error due to the type of ScopeTuple. The first entry of the tuple is expected to be `MoleculeScope<SomeType>` but is in fact `MoleculeScope<SomeType | undefined>`.

I would expect this code to work

**Comment by loganvolkers** [comment]
Thanks for this feedback! I'll try incorporating this into the next version.

Sorry for the slow response.

**Comment by loganvolkers** [comment]
Addressed in https://github.com/saasquatch/bunshi/pull/12
