### ISSUE TITLE
Feature request - read / write molecules

### ISSUE THREAD

**Issue by matthew-dean** [saasquatch/bunshi#13]
One thing I was hoping to do is replace [a custom implementation of Jotai](https://github.com/pmndrs/jotai/discussions/1422) that leverages `unstable_createStore` to read / write atoms in utility functions (outside a React context).

Jotai-molecules seems to get 99% of the way there in terms of defining global context, but stops short of updating atoms outside of components.

It would be great if this package would allow setting atoms / molecules outside of React (having read/write molecules).

**Comment by loganvolkers** [comment]
Hey @matthew-dean thanks for the feedback.

I believe that the newest versions of jotai have what you're looking for.

Sorry for the slow response, and please re-open this issue if there's anything else we can help with.
