### ISSUE TITLE
Question: live of state in atoms

### ISSUE THREAD

**Issue by carlesba** [saasquatch/bunshi#15]
I noticed atoms are kept in memory after scope is changed so they won't be created again when the scope is set back to an previous state.
Is there a way to manage that? Can we clear those atoms in any way? I remember that Jotai family provides so functions to evaluate the state of an atom when it's accessed so we can handle it validity.

Thanks for this awesome library.

**Comment by loganvolkers** [comment]
Thanks for the question @carlesba and sorry it's taken so long for you to get a response.

Can you help provide more details on what you were trying to achieve?

If you can provide a code example that will help me and others that might be facing a similar issue.
