### ISSUE TITLE
Firefox error after 2.0.2

### ISSUE THREAD

**Issue by alexlag** [saasquatch/bunshi#48]
In Firefox with bunshi@2.1.1 there is an error with WeakSet add calls. 

That might be because of Firefox [not supporting](https://caniuse.com/mdn-javascript_builtins_weakset_symbol_as_keys) non-registered symbols as keys.

**Comment by loganvolkers** [comment]
Thanks for the bug report!

We'll look at turning on [Browser Mode in vitest](https://vitest.dev/guide/browser) reproduce and confirm this issue.

**Comment by loganvolkers** [comment]
Reproduced this with [Browser Mode in vitest](https://vitest.dev/guide/browser) on the browser testing branch already. Looks like Firefox doesn't support non-registered symbols as keys in both [Weakmap](https://caniuse.com/mdn-javascript_builtins_weakmap_symbol_as_keys) and [Weakset](https://caniuse.com/mdn-javascript_builtins_weakset_symbol_as_keys).

This looks like it was introduced with the changes to lifecycle in 2.1.x

There should be a backwards-compatible fix. Will look to patch in 2.1.2 as a hot fix.

**Comment by loganvolkers** [comment]
Thanks for the report @alexlag - this has now been fixed and released in v2.1.2

Github actions to do automatic native in-browser testing have been added in #49 so that these kinds of regressions don't happen in the future.
