### ISSUE TITLE
remove `toSorted` usage because of browser compatibility

### ISSUE THREAD

**Issue by andrewdoro** [saasquatch/bunshi#52]
Recently, I've noticed runtime errors in my application attributed to the use of `toSorted` in the Bunshi library.

 Upon further investigation, I found that these errors predominantly occur in older browser versions that do not support this method. 
 
According to Caniuse, toSorted is a relatively recent addition to JavaScript and may not be widely supported across all browsers. It would be beneficial for us to consider removing the usage of toSorted from the library codebase to ensure better compatibility.

https://caniuse.com/mdn-javascript_builtins_array_tosorted

The sentry error happened here:
<img width="1064" alt="Screenshot 2024-02-23 at 14 29 24" src="https://github.com/saasquatch/bunshi/assets/17547035/9970d442-1c87-4030-8b2f-77709d72190b">

**Comment by loganvolkers** [comment]
Which browsers are you trying to support? This could be the first of many things that aren't supported in those browsers.

**Comment by andrewdoro** [comment]
@loganvolkers I think using the supported browsers from next.js would be the best choice.
https://nextjs.org/docs/architecture/supported-browsers

**Comment by loganvolkers** [comment]
Okay, it looks like https://github.com/amilajack/eslint-plugin-compat could be a good tool to test for browser incompatibilities.

**Comment by andrewdoro** [comment]
@loganvolkers I've added a PR for adding the plugin, but it can't detect array methods. See here for more details #54.

**Comment by loganvolkers** [comment]
Thanks for these PRs @andrewdoro - I'm going to work on getting these merged and released. Sorry for the delay.

**Comment by loganvolkers** [comment]
Releases in version 2.1.4
