### ISSUE TITLE
Not calling `getScope` in molecule definition results in shared atoms

### ISSUE THREAD

**Issue by mutewinter** [saasquatch/bunshi#8]
I noticed that if I don't call the `getScope` function during the creation of a `molecule` the atoms end up being shared on `useMolecule`. I'm also using both the `ScopeProvider` and `useMolecule(Molecule, { withScope: [Scope, value]});` syntax, if that is an issue.

Loving the library. Feel like this is solving a real issue with Jotai that should perhaps someday be in core.

**Comment by loganvolkers** [comment]
Thanks @mutewinter, that is operating as intended. Calling `getScope` or `getMolecule` is what creates the dependency tree, similar to calling `get` in an `atom`.

**Comment by mutewinter** [comment]
Gotcha. Feels like there should be a warning / error if it’s not called — if possible.

**Comment by loganvolkers** [comment]
I don't think it's possible to know a priori if a molecule should be scoped or not without that info. If you're using a global molecule (one without any calls to `getMolecule` or `getScope`) it is intended for it to be a singleton instance.

This could be better explained in the docs.

**Comment by mutewinter** [comment]
Yeah, docs makes sense. The examples re-using the molecule value to initialize an atom felt like a contrived example and not a real requirement.
